from typing import TypedDict, List, Dict, Any

class AgentCanvasState(TypedDict):
    domain_context: str          # Defines the current use-case (e.g., "Medical Triage" vs "Legal Review")
    raw_input_data: Dict[str, Any] # The blank canvas payload provided by the user
    messages: List[Dict[str, str]] # Conversation or execution history
    artifacts: Dict[str, Any]    # Outputs generated by individual agents
    current_step: str            # State tracking for the orchestrator
